kind = "web"
previewPath = "/"
title = "Nyxara"
version = "1.0.0"
id = "artifacts/nyxara"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23306

[services.development]
run = "pnpm --filter @workspace/nyxara run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nyxara", "run", "build" ]
publicDir = "artifacts/nyxara/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23306"
BASE_PATH = "/"
